[project]
name = "ohw24_proj_catalog_us"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alex Kerney <abk@mac.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
serve = "lektor server"

[dependencies]
lektor = ">=3.3.11,<3.4"
